export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_INGREDIENT = 'INIT_INGREDIENT';
export const INIT_INGREDIENT_ERR = 'INIT_INGREDIENT_ERR';
export const PLACE_ORDER = 'PLACE_ORDER';
export const PLACE_ORDER_ERR = 'PLACE_ORDER_ERR';
export const SHOW_MODEL = 'SHOW_MODEL';
export const HIDE_MODEL = 'HIDE_MODEL';